#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
GREY="\e[37m"
LRED="\e[91m"
LGREEN="\e[92m"
LYELLOW="\e[93m"
LBLUE="\e[94m"
LMAGENTA="\e[95m"
LCYAN="\e[96m"
LGREY="\e[97m"
BOLD="\e[1m"
RESET="\e[0m"

clear
echo -e "--------------------- \n$BOLD NORMAL: $RESET\n---------------------"
echo -e "$RED Hola $RESET"
echo -e "$GREEN Hola $RESET"
echo -e "$YELLOW Hola $RESET"
echo -e "$BLUE Hola $RESET"
echo -e "$MAGENTA Hola $RESET"
echo -e "$CYAN Hola $RESET"
echo -e "$GREY Hola $RESET"
echo -e "$LRED Hola $RESET"
echo -e "$LGREEN Hola $RESET"
echo -e "$LYELLOW Hola $RESET"
echo -e "$LBLUE Hola $RESET"
echo -e "$LMAGENTA Hola $RESET"
echo -e "$LCYAN Hola $RESET"
echo -e "$LGREY Hola $RESET"

echo -e "--------------------- \n$BOLD BOLD: $RESET\n---------------------"

echo -e "$BOLD$RED Hola $RESET"
echo -e "$BOLD$GREEN Hola $RESET"
echo -e "$BOLD$YELLOW Hola $RESET"
echo -e "$BOLD$BLUE Hola $RESET"
echo -e "$BOLD$MAGENTA Hola $RESET"
echo -e "$BOLD$CYAN Hola $RESET"
echo -e "$BOLD$GREY Hola $RESET"
echo -e "$BOLD$LRED Hola $RESET"
echo -e "$BOLD$LGREEN Hola $RESET"
echo -e "$BOLD$LYELLOW Hola $RESET"
echo -e "$BOLD$LBLUE Hola $RESET"
echo -e "$BOLD$LMAGENTA Hola $RESET"
echo -e "$BOLD$LCYAN Hola $RESET"
echo -e "$BOLD$LGREY Hola $RESET"